### ISSUE TITLE
More margin between words than between morphemes

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#101]
Perhaps there should be more margin between words than between morphemes? That would make things like this not look so spread out:
![image](https://user-images.githubusercontent.com/13228316/28383468-3b7d2a06-6c8f-11e7-8481-e8dec406eff8.png)

**Comment by nickatomlin** [comment]
To do this: add more margins between `<td>` elements with colSpan >= 1. When such elements are created, they could be given a className `longTD` or something that allows them to be selected as such.

EDIT: I attempted this, and it does not work because "dependent" rows don't adapt the same spacing. Not sure what to do here, since divs cannot be wrapped around `<td>` elements.

**Comment by sciepsilon** [comment]
A better way to handle this is proposed in issue #121.
