### ISSUE TITLE
Stop links from jumping on hover

### ISSUE THREAD

**Issue by sciepsilon** [Designist/Korpus#106]
Currently, when a title is just barely short enough to fit in the titles column of the index, hovering on it makes it overflow (because it becomes bold), such that the links after it jump down. It's particularly (only?) a problem when the index displays in a tiny left column, which we're trying to get it to stop doing.
 It's particularly (only?) a problem when the index displays in a tiny left column, which we're trying to get it to stop doing. This makes the index hard to use.

**Comment by nickatomlin** [comment]
No longer a problem! 218b50a0bb18cc86f3a0f4e8815036be8356462c
