### ISSUE TITLE
Missing annotations in ELAN files

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#112]
The undefined timestamps strike again. Often, when a timestamp appears but doesn't have an annotated time value, the corresponding dependent annotation vanishes. See (1:47) in the below example:
<img width="441" alt="screen shot 2017-07-27 at 12 08 22 pm" src="https://user-images.githubusercontent.com/13228316/28680751-42bdb948-72c5-11e7-8815-353db0f586ba.png">

**Comment by sciepsilon** [comment]
Based on manual inspection, Intro.json and fake_database.json correctly include all tiers in e4c490c. However, Intro isn't displaying (issue #122), so I can't verify that the site correctly includes all tiers.
