### ISSUE TITLE
Concatenate FLEx morphemes -> words

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#127]
FLEx morphemes are separated by a space currently, but it would be nice if we could combine them into single words, e.g., of form "sombo='je=fa=nga." IMPORTANT: it's easy to just leave a section blank in FLEx, so we should include "___" or something when an element doesn't align properly.

![image](https://user-images.githubusercontent.com/13228316/29189380-44eabf0c-7de4-11e7-9527-e97c2cc3589d.png)

**Comment by nickatomlin** [comment]
![image](https://user-images.githubusercontent.com/13228316/29322045-334dd6de-81aa-11e7-9155-b596ca84355a.png)

**Comment by sciepsilon** [comment]
New desired behavior (I'll program this): Missing morphemes are replaced with three stars. Try to detect any missing morph delimiters (+, =, -) by matching existing morphs to the word (but don't try too hard). If a morph delimiter is detected, include it among the stars. 
So for example: jipaen // ji=paen // ji=**** // come=****

**Comment by sciepsilon** [comment]
Closed in 9e8af41
