### ISSUE TITLE
Dashes in concatenated FLEx glosses

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#129]
Concatenating the FLEx glosses doesn't work well with dashes.
![image](https://user-images.githubusercontent.com/13228316/29427651-78c95ca6-8358-11e7-9848-77a1c4636b84.png)
![image](https://user-images.githubusercontent.com/13228316/29427672-8a7eb81a-8358-11e7-9e9b-756988ea20d0.png)

**Comment by nickatomlin** [comment]
More bad concatenation ("dadold man"):
<img width="473" alt="screen shot 2017-08-22 at 2 43 26 pm" src="https://user-images.githubusercontent.com/13228316/29581740-502939da-8748-11e7-9e0e-4e42e60e68f5.png">

**Comment by sciepsilon** [comment]
What behavior do we want? How about: "yaya-ccasheye", "dad-old man"? Or would "dad-old_man" be better?

**Comment by sciepsilon** [comment]
Part of this issue (including '-' in the gloss of each suffix) was fixed in 9e8af41.

**Comment by sciepsilon** [comment]
Essentially fixed in d184807. Still some weirdness: 
![image](https://user-images.githubusercontent.com/19783656/29732802-47dc15e6-89b8-11e7-9ee0-f3088a6272b7.png)
(one of many examples from "Chiga, tsanda, pushesu...")

**Comment by sciepsilon** [comment]
Turns out this was due to a quirk of the entry for "te" in the FLEx lexicon. Now that te has been re-classified as an enclitic rather than a clitic, the problem should be fixed, although standalone "te" will now appear with an erroneous-ish initial equals sign.
