### ISSUE TITLE
Story index

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#28]
We need an index to select a story, akin to [the Moro text collection](http://linguistics.berkeley.edu/moro/#/text).

**Comment by sciepsilon** [comment]
Probably have one html page per text, which just points to the json and mp3/mp4 files associated with that text, as well as pointing to the standard files like settings.js. An index page links to all the html pages.

**Comment by nickatomlin** [comment]
Working as of 41799419357ee73f54d9bc2215fe9a9f639ee379.
