### ISSUE TITLE
Increase settings width for untimed display

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#59]
There's some overlap between the settings and the TextDisplay:

![image](https://user-images.githubusercontent.com/13228316/28172607-0487df5c-67ba-11e7-97c1-ec4f67677bdc.png)

**Comment by sciepsilon** [comment]
Instead of / in addition to increasing the settings width, we could rename certain settings (e.g. "citation form" instead of "morpheme (citation form)") and/or allow linebreaks in each checkbox label.

**Comment by nickatomlin** [comment]
This is a weird bug that only shows up in a very particular circumstance, i.e., when the user leaves a TimedTextDisplay page with video enabled and views an untimed one. Somehow the text "fills the space" left by the larger, video display and then overflows.

**Comment by nickatomlin** [comment]
Fixed sometime before 4477b718785dc14fcdd8ff559b2f4e5e484b3350.
