### ISSUE TITLE
Play audio

### ISSUE THREAD

**Issue by sciepsilon** [Designist/Korpus#6]
Use scrubber bar as normal, or click sentence timestamp to navigate audio.

**Comment by sciepsilon** [comment]
Use scrubber bar as normal, or click sentence timestamp to navigate audio.

**Comment by nickatomlin** [comment]
Partially done as of 9d4588f27ddcac6da32ef73f35ad4088e3177fc3. Still missing the ability to click on sentence timestamps and jump to that point in the audio.

**Comment by nickatomlin** [comment]
Working as of c3fbd61cc8cd6b48a1c1d5cd0a6e3b2b3ddaa4d4.
