### ISSUE TITLE
Link audio/video files to JSON

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#60]
Link the corresponding audio and video files in each JSON file, and implement it. We currently have the Intro.mp4 video appearing for all TimedTextDisplays, which needs to change ASAP.

**Comment by nickatomlin** [comment]
Needs to account for:
- Video/audio
- Audio only
- Video only

**Comment by sciepsilon** [comment]
Working in e798c91.

**Comment by sciepsilon** [comment]
When there's video but no audio, display video right away (as if user has already hit the "show video" button).

**Comment by sciepsilon** [comment]
Working in 4477b71.
