### ISSUE TITLE
Intro to Intro2

### ISSUE THREAD

**Issue by sciepsilon** [Designist/Korpus#75]
Different buggy behavior when going from Intro with or without video, to Intro2, both when changing the url and when using the index.

**Comment by nickatomlin** [comment]
The only buggy behavior now is from Intro2 -> Intro, when the video refuses to disappear.

01716719c7c3e4bc776dbcd8305e502f2892b94d

**Comment by nickatomlin** [comment]
Fixed as of 4477b718785dc14fcdd8ff559b2f4e5e484b3350.

Code seems very fragile and might need to be rewritten.

**Comment by sciepsilon** [comment]
Working in 4477b71.
