### ISSUE TITLE
ELAN glosses incomplete preprocessing (Maks's bug)

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#86]
The ELAN preprocessing is not working correctly. Specifically, the words at the ends of some sentences are not being glossed, even though they appear in the `.eaf` file:
![image](https://user-images.githubusercontent.com/13228316/28288360-f458e576-6b0c-11e7-8404-3dec168ce7c5.png)
These words do _not_ appear in the `.json` file, so the issue must be on the preprocessing side.

**Comment by sciepsilon** [comment]
Working in ba5e38f. The bug was from relying on timeslots' millisecond value (which is occasionally missing), fixed by looking at timeslot IDs instead.
