### ISSUE TITLE
Remove/hide unnecessary tiers

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#88]
FLEx tiers are somewhat consistent, so we can force hiding the following tiers:
- variantTypes
- hn (numbering)

These tiers might be useful but should be hidden by default:
- parts of speech
- morpheme spelling differences (forma típico vs. texta, choose one)

**Comment by nickatomlin** [comment]
This is no longer an alpha requirement -- I've removed the necessary tiers for a working demo in the ReactJS file, no matter how hacky it may be.

**Comment by sciepsilon** [comment]
Closed in 750dec9.
