### ISSUE TITLE
Weird empty tiers

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#90]
There are some weird empty tiers (with only "T" and "j" respectively) in the 001 story. Is this a problem on the backend or was this just bad glossing?
![image](https://user-images.githubusercontent.com/13228316/28333893-662f5b02-6bc7-11e7-8d1a-3370e0000724.png)

**Comment by sciepsilon** [comment]
Just weird/bad glossing. Our backend is accurately displaying the content of 001.xml.
