### ISSUE TITLE
Palabra inglés tier

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#91]
The Palabra inglés tier is puzzling and incorrectly named. In the screenshot below, it is the second row. I would expect it to match the main A'ingae gloss, but it does not. Is this bad glossing? Or bad preprocessing?

Also, it's not English, so change the name.
![image](https://user-images.githubusercontent.com/13228316/28334056-e54819a6-6bc7-11e7-88e1-9edd7cb71d62.png)

**Comment by sciepsilon** [comment]
The name was fixed in 5c28a0d. Still need to fix missing morphemes.

**Comment by sciepsilon** [comment]
Missing morphemes was just an instance of the punctuation bug, fixed elsewhere.
