### ISSUE TITLE
Frase a'ingae tier

### ISSUE THREAD

**Issue by nickatomlin** [Designist/Korpus#94]
[Here's a bug in story 103](https://designist.github.io/Korpus/#/story/103):

![image](https://user-images.githubusercontent.com/13228316/28336642-c7a7dd6a-6bd0-11e7-91e3-7bc997ccbb54.png)

There's a `frase a'ingae` tier linked to this line of translation: "Así es como se crearon las personas de color negro." This is not a'ingae.

**Comment by sciepsilon** [comment]
Actually, this looks like a glossing error. From 103.xml, line 903: 
"<item type="gls" lang="con-Latn-EC">Así es como se crearon las personas de color negro. </item>"
I've manually changed the lang attribute for now.

**Comment by nickatomlin** [comment]
Seems like this is an issue with FLEx config. Closing for now.
